stages:
  extract_data:
    cmd: python extract_data.py
    deps:
    - extract_data.py
    outs:
    - data/dataset.csv
  modify_data:
    cmd: python modify_data.py
    deps:
    - data/raw_dataset.csv
    - modify_data.py
    outs:
    - data/modified_dataset.csv
