stages:
  extract_data:
    cmd: python training_pipeline/extract_data.py
    deps:
    - training_pipeline/extract_data.py
    outs:
    - data/dataset.csv

  modify_data:
    cmd: python training_pipeline/modify_data.py
    deps:
    - data/raw_dataset.csv
    - training_pipeline/modify_data.py
    outs:
    - data/modified_dataset.csv

  train_model:
    cmd: python training_pipeline/train_model.py
    deps:
    - data/modified_dataset.csv
    - train_model.py
    outs:
    - models/
