# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: pip install -r requirements.txt
# RUN dvc remote modify myremote --local access_key_id ${S3_ACCESS_KEY_ID}
# RUN dvc remote modify myremote --local secret_access_key $S3_SECRET_ACCESS_KEY
      - run: dvc remote modify myremote --local access_key_id ${{ secrets.S3_ACCESS_KEY_ID }}
      - run: dvc remote modify myremote --local secret_access_key ${{ secrets.S3_SECRET_ACCESS_KEY }}
      - run: |
          dvc pull
#          Flag to extract only the model
      - run: flyctl deploy --remote-only --Dockerfile Dockerfile
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

